### ISSUE TITLE
Issue displaying charts when axis changes unit

### ISSUE THREAD

**Issue by b-per** [tonka3000/raycast-charts-extension#1]
Hi! I have installed your extension and was looking at some pages and I just saw that there is a small bug when displaying results if the axis changes unit (e.g. going from 1-9 to 10-99)

![raycast-charts 2022-07-21 at 20 11 47](https://user-images.githubusercontent.com/8754100/180284370-afab5bd3-0d2b-409b-87a6-679ec0c84e8a.png)

**Comment by tonka3000** [comment]
Hey @b-per ,

I've replace the ascii chart with an SVG based on and therefore the issue should not exist anymore 😁.
Update the `main` branch to the latest revision to get the SVG version.

![CleanShot 2023-07-30 at 22 02 15@2x](https://github.com/tonka3000/raycast-charts-extension/assets/3163807/cefc0f95-6afd-403b-be2f-be8184077d11)
